# Generated by Django 5.0.7 on 2024-07-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_application_options_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='classtype',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
